### PR TITLE
Replaces lobby music

### PR DESCRIPTION
**Pull request by Scinexx**
Replaces lobby music with these three

1. Classic Robocop: [Link](https://www.youtube.com/watch?v=dCPWE4WexM8&t=55s)
2. Beatnik Lobby 1 (Original): [Link](https://drive.google.com/file/d/1bNverulOhEuZc7c61r53f42yqkKQq617/view?usp=sharing)
3. Beatnik Lobby 2 (Original): [Link](https://drive.google.com/file/d/12r96yBPvy-sv8FDLI7Yt1hEg6pA-XGih/view?usp=sharing)

### CODE REVIEW

**Comment by Scinexx** [comment]
yeah we need to the shit newer hippie and tg has where they can have as many songs as we want, right now were limited to 3

**Comment by GeneralGoose** [comment]
no we're not

**Comment by AffectedArc07** [comment]
Doesnt change anything here but next time dont use your master branch

**Comment by krillbill01** [comment]
Looks good, if you’re ready for this to merged scienx, just say

**Comment by AffectedArc07** [comment]
Music is fucking amazing

**Pull request merged**
