### PR TITLE
Adds mapmerge2 + mapmerges maps

### PR DESCRIPTION
**Pull request by praisenarsie**
Adds stuff to .gitignore and removes old mapmerges.

yuuuuuuuuuuup, this is gonna be the biggest PR for beatnik

### CODE REVIEW

**Comment by praisenarsie** [comment]
oh yeah credits to @spacemaniac

**Comment by krillbill01** [comment]
could you explain this for us smooth brains

**Comment by AffectedArc07** [comment]
Bascially mapmerge is a PR friendly tool for making map edits without a bajillion diffs

**Comment by kingoftheautism** [comment]
+3 mil. lines? oh my

**Comment by praisenarsie** [comment]
i suggest merging this asap

**Comment by AffectedArc07** [comment]
Image
When I am home

**Pull request merged**
